version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - terwer
    assignees:
      - terwer
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - "npm dependencies"
      - "npm"

  - package-ecosystem: npm
    directory: "/libs/zhi-picgo-core"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - terwer
    assignees:
      - terwer
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - "npm dependencies"
      - "npm"
      - "picgo-core"

  - package-ecosystem: npm
    directory: "/libs/zhi-picgo-siyuan"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - terwer
    assignees:
      - terwer
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - "npm dependencies"
      - "npm"
      - "picgo-siyuan"

  - package-ecosystem: npm
    directory: "/packages/picgo-plugin-bootstrap"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - terwer
    assignees:
      - terwer
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - "npm dependencies"
      - "npm"
      - "bootstrap"

  - package-ecosystem: npm
    directory: "/packages/picgo-plugin-app"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - terwer
    assignees:
      - terwer
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - "npm dependencies"
      - "npm"
      - "app"

  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - terwer
    assignees:
      - terwer
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - "github actions"
      - "ci"